# Generated by Django 4.1.4 on 2022-12-08 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=150)),
                ('short_content', models.CharField(max_length=200)),
                ('long_content', models.TextField()),
                ('created_by', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField()),
            ],
        ),
    ]
